/* Writes the search tables of solver_ida.c for the RV32I programs.
 *
 * Usage: gen_tables OUTPUT_DIR
 *
 *   tables.s       assembler data: permutation, orientation (halfwords),
 *                  permutation_distance, orientation_distance (bytes)
 *   tables.h       the same tables as C constants
 *   states_d11.txt every distance-11 state, one per line, in rank order
 */
#define main solver_ida_main
#include "../solver_ida.c"
#undef main

static FILE *open_output(const char *dir, const char *name)
{
    char path[1024];
    snprintf(path, sizeof path, "%s/%s", dir, name);
    FILE *file = fopen(path, "w");
    if (!file)
        perror(path);
    return file;
}

static int close_output(FILE *file)
{
    int write_error = ferror(file);
    return fclose(file) == 0 && !write_error;
}

static void asm_rows(FILE *out, const char *directive, const uint16_t *values,
                     unsigned count)
{
    for (unsigned i = 0; i < count; ++i)
        fprintf(out, "%s%u%s", i % 16 ? ", " : directive, values[i],
                i % 16 == 15 || i + 1 == count ? "\n" : "");
}

static void asm_byte_rows(FILE *out, const uint8_t *values, unsigned count)
{
    for (unsigned i = 0; i < count; ++i)
        fprintf(out, "%s%u%s", i % 16 ? ", " : "    .byte ", values[i],
                i % 16 == 15 || i + 1 == count ? "\n" : "");
}

static int write_asm(const char *dir)
{
    FILE *out = open_output(dir, "tables.s");
    if (!out)
        return 0;
    fputs("# Generated by rv32/gen_tables.c from solver_ida.c; do not edit.\n"
          "# Rows are faces R, B, D; each entry is one quarter turn.\n"
          ".data\n.align 2\npermutation:\n",
          out);
    for (unsigned face = 0; face < 3; ++face)
        asm_rows(out, "    .half ", permutation[face], PERMUTATIONS);
    fputs("orientation:\n", out);
    for (unsigned face = 0; face < 3; ++face)
        asm_rows(out, "    .half ", orientation[face], ORIENTATIONS);
    fputs("permutation_distance:\n", out);
    asm_byte_rows(out, permutation_distance, PERMUTATIONS);
    fputs("orientation_distance:\n", out);
    asm_byte_rows(out, orientation_distance, ORIENTATIONS);
    return close_output(out);
}

static void c_rows(FILE *out, const uint16_t *values, unsigned count)
{
    for (unsigned i = 0; i < count; ++i)
        fprintf(out, "%s%u,%s", i % 12 ? " " : "        ", values[i],
                i % 12 == 11 || i + 1 == count ? "\n" : "");
}

static void c_byte_rows(FILE *out, const uint8_t *values, unsigned count)
{
    for (unsigned i = 0; i < count; ++i)
        fprintf(out, "%s%u,%s", i % 16 ? " " : "    ", values[i],
                i % 16 == 15 || i + 1 == count ? "\n" : "");
}

static int write_c(const char *dir)
{
    FILE *out = open_output(dir, "tables.h");
    if (!out)
        return 0;
    fputs("/* Generated by rv32/gen_tables.c from solver_ida.c; do not edit. */\n"
          "#include <stdint.h>\n\n"
          "static const uint16_t permutation[3][5040] = {\n",
          out);
    for (unsigned face = 0; face < 3; ++face) {
        fputs("    {\n", out);
        c_rows(out, permutation[face], PERMUTATIONS);
        fputs("    },\n", out);
    }
    fputs("};\n\nstatic const uint16_t orientation[3][729] = {\n", out);
    for (unsigned face = 0; face < 3; ++face) {
        fputs("    {\n", out);
        c_rows(out, orientation[face], ORIENTATIONS);
        fputs("    },\n", out);
    }
    fputs("};\n\nstatic const uint8_t permutation_distance[5040] = {\n", out);
    c_byte_rows(out, permutation_distance, PERMUTATIONS);
    fputs("};\n\nstatic const uint8_t orientation_distance[729] = {\n", out);
    c_byte_rows(out, orientation_distance, ORIENTATIONS);
    fputs("};\n", out);
    return close_output(out);
}

static int write_states(const char *dir, const uint8_t *distance)
{
    FILE *out = open_output(dir, "states_d11.txt");
    if (!out)
        return 0;
    unsigned count = 0;
    for (uint32_t rank = 0; rank < STATES; ++rank) {
        if (distance[rank] != 11)
            continue;
        state_t state;
        unrank_state(rank, &state);
        for (unsigned i = 0; i < CUBIES; ++i)
            fputc('1' + state.p[i], out);
        for (unsigned i = 0; i < CUBIES; ++i)
            fputc('1' + state.o[i], out);
        fputc('\n', out);
        ++count;
    }
    return close_output(out) && count == 2644;
}

int main(int argc, char **argv)
{
    uint8_t diameter;
    if (argc != 2) {
        fputs("usage: gen_tables OUTPUT_DIR\n", stderr);
        return 2;
    }
    if (!init_tables()) {
        fputs("incomplete heuristic tables\n", stderr);
        return 1;
    }
    uint8_t *distance = build_table(&diameter);
    if (!distance || diameter != 11) {
        fputs("BFS oracle failed\n", stderr);
        free(distance);
        return 1;
    }
    int ok = write_asm(argv[1]) && write_c(argv[1]) &&
             write_states(argv[1], distance);
    free(distance);
    if (!ok)
        fputs("could not write the generated files\n", stderr);
    return !ok;
}
